import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className='content' style={{
          textAlign: 'center',
          lineHeight: 2
        }}>
          <div style={{ borderRadius: 30 }}><img style={{ width: '20%' }} src="https://images-na.ssl-images-amazon.com/images/G/02/aplusautomation/vendorimages/0b925aaf-0920-4019-a78e-dbe23cc1d1fa.jpg._CB536181688_.jpg" /></div>
          <h3 style={{ fontSize: 28 }}>Bolaji</h3>

          <p style={{ fontSize: 18 }}>
            Hello, I’m Bolaji. I’m an aspiring software engineer.
          </p>
          <p style={{ fontSize: 18 }}>
            (This is a sample website.)
          </p>

          <h3>Blog</h3>
          <p style={{ fontSize: 18 }}><a style={{ color: 'blue' }} href="posts/first-post">First post</a></p>
          <p style={{ fontSize: 18 }}>Nov 1 2023</p>
          <p style={{ fontSize: 18 }}><a style={{ color: 'blue' }} href="posts/second-post">Second post</a></p>
          <p style={{ fontSize: 18 }}>Nov 2 2023</p>
        </div>
      </main>
    </>
  )
}
